import type { NextPage } from 'next'
import Head from "next/head";
import Script from "next/script";

import Home from "../components/home";

const HomePage: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Testing Equal-web</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home />
      <Script id="user-way">{`window.interdeal = { "sitekey": "fc266cf13154c438855838cb9d7d8969", "Position": "Left", "Menulang": "EN", "domains": { "js": "https://cdn.equalweb.com/", "acc": "https://access.equalweb.com/" }, "btnStyle": { "vPosition": [ "80%", null ], "scale": [ "0.8", "0.8" ], "icon": { "type": 7, "shape": "semicircle", "outline": false } } }; (function(doc, head, body){ var coreCall = doc.createElement('script'); coreCall.src = 'https://cdn.equalweb.com/core/4.0.4/accessibility.js'; coreCall.defer = true; coreCall.integrity = 'sha512-LDvqiv8qYdF1MIqxiGZrvcDsmN6cZy0u0l23Dj7TVXmkVSNyzjtkcll8uCb8EGdwDVHjvisVYsAWuwTf6Mpu8g=='; coreCall.crossOrigin = 'anonymous'; coreCall.setAttribute('data-cfasync', true ); body? body.appendChild(coreCall) : head.appendChild(coreCall); })(document, document.head, document.body); `}</Script>
    </div>
  );
};

export default HomePage;

